var gv_searchData= null;
var defaultMasterHeight=0;var defaultDetailHeight=0;function initLayout(splitSize){if($('#ctm_mg_wrap').length>0&&$('#ctm_dg_wrap').length==0){$(window).bind('resize',function(event){$('#ctm_mg_wrap').height($('#ct_wrap').height()-$('#ctm_sech_wrap').outerHeight(true)-10);$('#ctm_mg_wrap').width($('#ctm_mg_wrap').parent().width());}).trigger('resize');}
else if($('#ctm_mg_wrap').length>0&&$('#ctm_dg_wrap').length>0){$(window).bind('resize',function(event){if(typeof splitSize=='undefined'||splitSize==null){defaultMasterHeight=Math.floor(($('#ct_wrap').height()-$('#ctm_sech_wrap').outerHeight(true))/2);}else{defaultMasterHeight=splitSize;}
if(typeof event.which=='undefined'){$('#ctm_mg_wrap').height(defaultMasterHeight-10);$('#ctm_dg_wrap').height($('#ct_wrap').height()-$('#ctm_sech_wrap').outerHeight(true)-$('#ctm_mg_wrap').outerHeight(true)-10);}else{$('#ctm_dg_wrap').height($('#ct_wrap').height()-$('#ctm_sech_wrap').outerHeight(true)-$('#ctm_mg_wrap').outerHeight(true)-10);}
$('#ctm_mg_wrap').width($('#ctm_mg_wrap').parent().width());$('#ctm_dg_wrap').width($('#ctm_dg_wrap').parent().width());}).trigger('resize');$('#ctm_mg_wrap').resizable({handles:'s'});}
else if($('#ctd_form_wrap').length>0&&$('#ctd_dg_wrap').length==0){$(window).bind('resize',function(event){$('#ctd_form_wrap').height($('#ct_wrap').height()-1);}).trigger('resize');}
else if($('#ctd_form_wrap').length>0&&$('#ctd_dg_wrap').length>0){$(window).bind('resize',function(event){if(typeof splitSize=='undefined'||splitSize==null)
defaultDetailHeight=Math.floor($('#ct_wrap').height()/2);else
defaultDetailHeight=splitSize;if(typeof event.which=='undefined'){if($('#ctd_dg_wrap').css('display')=='none'){$('#ctd_dg_wrap').height(0);$('#ctd_form_wrap').height($('#ct_wrap').height()-1);}else{$('#ctd_dg_wrap').height(defaultDetailHeight);$('#ctd_form_wrap').height($('#ct_wrap').height()-$('#ctd_dg_wrap').outerHeight(true)-1);}}else{$('#ctd_form_wrap').height($('#ct_wrap').height()-$('#ctd_dg_wrap').outerHeight(true)-1);$('#ctd_dg_wrap').css('top',0);}
$('#ctd_dg_wrap').width($('#ctd_dg_wrap').parent().width());}).trigger('resize');$('#ctd_dg_wrap').resizable({handles:'n'});}
else if($('#ctu_wrap').length>0){if($('#ctu_no_resize').length>0&&$('.ctu_resize').length>0){$(window).bind('resize',function(e){$('.ctu_resize').height($('#ctu_wrap').height()-$('#ctu_no_resize').outerHeight(true)-10);}).trigger('resize');}}
if($('#sech_extwrap').length>0){$('#ctm_sech_wrap').css('padding','4px 0 2px 0');$('#sech_extwrap').hide();$('#sech_extbtn').click(function(e){if($('#sech_extbtn').attr('class')=='down'){$('#ctm_sech_wrap').css('padding','4px 0 6px 0');$('#sech_extbtn').attr('class','up');$('#sech_extwrap').show();}else{$('#ctm_sech_wrap').css('padding','4px 0 2px 0');$('#sech_extbtn').attr('class','down');$('#sech_extwrap').hide();}
refreshLayout();});}
if($('#form_extwrap').length>0){$('#form_extwrap').hide();$('#form_extbtn').click(function(e){if($('#form_extbtn').attr('class')=='down'){$('#form_extbtn').attr('class','up');$('#form_extwrap').show();}else{$('#form_extbtn').attr('class','down');$('#form_extwrap').hide();}
refreshLayout();});}}
function refreshLayout(){$(window).triggerHandler('resize');}
function layoutRefresh(){if($('#ctm_mg_wrap').length>0&&$('#ctm_dg_wrap').length==0){$('#ctm_mg_wrap').height($('#ct_wrap').height()-$('#ctm_sech_wrap').outerHeight(true)-10);$('#ctm_mg_wrap').width($('#ctm_mg_wrap').parent().width());}
else if($('#ctm_mg_wrap').length>0&&$('#ctm_dg_wrap').length>0){$('#ctm_mg_wrap').height(defaultMasterHeight);$('#ctm_dg_wrap').height($('#ct_wrap').height()-$('#ctm_sech_wrap').outerHeight(true)-$('#ctm_mg_wrap').outerHeight(true));$('#ctm_mg_wrap').width($('#ctm_mg_wrap').parent().width()-20);$('#ctm_dg_wrap').width($('#ctm_dg_wrap').parent().width()-20);}
else if($('#ctd_form_wrap').length>0&&$('#ctd_dg_wrap').length==0){$('#ctd_form_wrap').height($('#ct_wrap').height()-1);}
else if($('#ctd_form_wrap').length>0&&$('#ctd_dg_wrap').length>0){if($('#ctd_dg_wrap').css('display')=='none'){$('#ctd_dg_wrap').height(0);$('#ctd_form_wrap').height($('#ct_wrap').height()-15);}else{$('#ctd_dg_wrap').height(defaultDetailHeight);$('#ctd_form_wrap').height($('#ct_wrap').height()-$('#ctd_dg_wrap').outerHeight(true));}
$('#ctd_dg_wrap').width($('#ctd_dg_wrap').parent().width());}
else if($('#ctu_wrap').length>0){if($('#ctu_no_resize').length>0&&$('.ctu_resize').length>0){$('.ctu_resize').height($('#ctu_wrap').height()-$('#ctu_no_resize').outerHeight(true)-10);}}}
function fn_cmnBtn_onclick(type){switch(type){case"RET":cfn_retrieve&&cfn_retrieve(1);break;case"LIST":cfn_list&&cfn_list();break;case"NEW":cfn_new&&cfn_new();break;case"DEL":cfn_del&&cfn_del();break;case"SAVE":cfn_save&&cfn_save();break;case"COPY":cfn_copy&&cfn_copy();break;case"INIT":cfn_init&&cfn_init();break;case"EXECUTE":cfn_execute&&cfn_execute();break;case"PRINT":cfn_print&&cfn_print();break;case"EXCELDOWN":cfn_exceldown&&cfn_exceldown();break;case"USER1":cfn_userbtn1&&cfn_userbtn1();break;case"USER2":cfn_userbtn2&&cfn_userbtn2();break;case"USER3":cfn_userbtn3&&cfn_userbtn3();break;case"USER4":cfn_userbtn4&&cfn_userbtn4();break;case"USER5":cfn_userbtn5&&cfn_userbtn5();break;default:break;}}
function setCommBtn(id,flag,text,iconname){if(flag)
$('#cBtn'+id).show();else
$('#cBtn'+id).hide();if(fn_empty(text)==false)
$('#cBtn'+id).val(text);if(fn_empty(iconname)==false)
$('#cBtn'+id).css('background','url("/images/'+iconname+'") 3px 2px no-repeat').css('background-size','16px auto');}
function setCommBtnSeq(list){var v_ret=$('#cbtn_ret').clone();var v_list=$('#cbtn_list').clone();var v_new=$('#cbtn_new').clone();var v_del=$('#cbtn_del').clone();var v_save=$('#cbtn_save').clone();var v_copy=$('#cbtn_copy').clone();var v_init=$('#cbtn_init').clone();var v_exec=$('#cbtn_execute').clone();var v_print=$('#cbtn_print').clone();var v_excel=$('#cbtn_exceldown').clone();var v_user1=$('#cbtn_user1').clone();var v_user2=$('#cbtn_user2').clone();var v_user3=$('#cbtn_user3').clone();var v_user4=$('#cbtn_user4').clone();var v_user5=$('#cbtn_user5').clone();for(var i=0,len=list.length;i<len;i++){if(list[i]=='ret'){$('#cbtn_ret').remove();$('#ctw_btns').append(v_ret).append(' ');}else if(list[i]=='list'){$('#cbtn_list').remove();$('#ctw_btns').append(v_list).append(' ');}else if(list[i]=='new'){$('#cbtn_new').remove();$('#ctw_btns').append(v_new).append(' ');}else if(list[i]=='del'){$('#cbtn_del').remove();$('#ctw_btns').append(v_del).append(' ');}else if(list[i]=='save'){$('#cbtn_save').remove();$('#ctw_btns').append(v_save).append(' ');}else if(list[i]=='copy'){$('#cbtn_copy').remove();$('#ctw_btns').append(v_copy).append(' ');}else if(list[i]=='init'){$('#cbtn_init').remove();$('#ctw_btns').append(v_init).append(' ');}else if(list[i]=='execute'){$('#cbtn_execute').remove();$('#ctw_btns').append(v_exec).append(' ');}else if(list[i]=='print'){$('#cbtn_print').remove();$('#ctw_btns').append(v_print).append(' ');}else if(list[i]=='exceldown'){$('#cbtn_exceldown').remove();$('#ctw_btns').append(v_excel).append(' ');}else if(list[i]=='user1'){$('#cbtn_user1').remove();$('#ctw_btns').append(v_user1).append(' ');}else if(list[i]=='user2'){$('#cbtn_user2').remove();$('#ctw_btns').append(v_user2).append(' ');}else if(list[i]=='user3'){$('#cbtn_user3').remove();$('#ctw_btns').append(v_user3).append(' ');}else if(list[i]=='user4'){$('#cbtn_user4').remove();$('#ctw_btns').append(v_user4).append(' ');}else if(list[i]=='user5'){$('#cbtn_user5').remove();$('#ctw_btns').append(v_user5).append(' ');}}}
function fn_pageMove(url,arrParam){var form=$('<form></form>');form.attr('action',url);form.attr('method','get');form.appendTo('body');if(fn_empty(arrParam)==false){$.each(arrParam,function(key,value){form.append('<input type="hidden" name="'+key+'" value="'+value+'">');});}
if(fn_empty(gv_searchData)==false){if(typeof gv_searchData=='object')
gv_searchData=JSON.stringify(gv_searchData);else
gv_searchData=gv_searchData;form.append('<input type="hidden" name="SEARCHDATA" value="'+gv_searchData.replace(/\"/g,'||')+'">');}
if(!chk_event) {window.onbeforeunload = null;} form.submit();}
function fn_initSearch(searchData){gv_searchData=fn_replaceAll(searchData,'||','"');if(fn_empty(gv_searchData)==false){gv_searchData=JSON.parse(gv_searchData);$.each(gv_searchData,function(key,value){$('#ctm_sech_wrap').find('form').find('[name="'+key+'"]').val(value);});cfn_retrieve();}}